export const LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const LOGIN_FAILURE = "USER_LOGIN_FAILURE";
export const USER_LOGIN_TEST = "TEST";

// export type LOGIN_REQUEST = "USER_LOGIN_REQUEST";
// export type LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
// export type LOGIN_FAILURE = "USER_LOGIN_FAILURE";
// export type USER_LOGIN_TEST = "TEST";

// export type LOGIN_ACTION_TYPES = LOGIN_REQUEST | LOGIN_SUCCESS | LOGIN_FAILURE | USER_LOGIN_TEST;

// export default LOGIN_ACTION_TYPES
// {
//     LOGIN_REQUEST
//     LOGIN_SUCCESS
//     LOGIN_FAILURE
// }